SELECT APELLIDO, OFICIO, SALARIO, FECHA_ALT 
FROM EMPLE 
WHERE UPPER(OFICIO) = (SELECT OFICIO 
                        FROM EMPLE 
                        WHERE UPPER(APELLIDO)='JIMENEZ') 
                    OR SALARIO >= (SELECT SALARIO 
                        FROM EMPLE 
                        WHERE UPPER(APELLIDO)='FERNANDEZ'))



SELECT OFICIO FROM EMPLE WHERE UPPER(APELLIDO)='JIMENEZ' 

SELECT SALARIO FROM EMPLE WHERE UPPER(APELLIDO)='FERNANDEZ'