--ej1
SELECT ACTOR_NOMBRE
FROM ACTOR
WHERE TIPO_DEBUT IS NOT NULL AND MONTHS_BETWEEN(SYSDATE, FECHA_NAC) < 20*12;

--ej2
SELECT ACTOR_NOMBRE
FROM ACTOR
JOIN REPARTO ON REPARTO.ACTOR_ID = ACTOR.ACTOR_ID
JOIN SERIE ON SERIE.SERIE_ID = REPARTO.SERIE_ID
WHERE DEBUT IS NULL;

--EJ3
SELECT ACTOR_NOMBRE
FROM ACTOR
WHERE TIPO_DEBUT = 'CINE' AND FECHA_NAC = (SELECT MAX(FECHA_NAC) FROM ACTOR WHERE TIPO_DEBUT = 'CINE');

--EJ4
SELECT ACTOR.ACTOR_NOMBRE, COUNT(*)
FROM REPARTO
JOIN ACTOR ON ACTOR.ACTOR_ID = REPARTO.ACTOR_ID
GROUP BY REPARTO.ACTOR_ID, ACTOR.ACTOR_NOMBRE
HAVING COUNT(*) > 1;

--EJ5
SELECT SERIE_TITULO, TEMPORADA, COUNT(*) "Número de capítulos"
FROM CAPITULO
JOIN SERIE ON SERIE.SERIE_ID = CAPITULO.SERIE_ID
GROUP BY SERIE_TITULO, TEMPORADA;

--ej6
SELECT SERIE_TITULO, NVL(TO_CHAR(TEMPORADA), 'No tiene'), COUNT(CAPITULO) "Número de capítulos"
FROM CAPITULO
RIGHT JOIN SERIE ON SERIE.SERIE_ID = CAPITULO.SERIE_ID
GROUP BY SERIE_TITULO, TEMPORADA;

--ej7
SELECT SERIE_TITULO, COUNT(*)
FROM REPARTO
JOIN SERIE ON SERIE.SERIE_ID = REPARTO.SERIE_ID
GROUP BY REPARTO.SERIE_ID, SERIE_TITULO
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM REPARTO GROUP BY SERIE_ID);

--ej8
SELECT ACTOR_NOMBRE, NACIONALIDAD, FECHA_NAC
FROM ACTOR
ORDER BY FECHA_NAC ASC, NACIONALIDAD ASC;

--ej9
INSERT INTO CAPITULO
SELECT SERIE_ID, 2, 2, 'Examen BBDD', 45
FROM CAPITULO
GROUP BY SERIE_ID
HAVING COUNT(*) = (SELECT MIN(COUNT(*)) FROM CAPITULO GROUP BY SERIE_ID);

--ej10
UPDATE ACTOR 
SET TIPO_DEBUT = 
    (SELECT TIPO_DEBUT 
    FROM ACTOR
    GROUP BY TIPO_DEBUT
    HAVING LENGTH(TIPO_DEBUT) = 
        (SELECT MIN(LENGTH(TIPO_DEBUT)) FROM ACTOR))
WHERE TIPO_DEBUT IS NULL;