--TABLAS DEPART Y EMPLE
--EJ1
SELECT APELLIDO,SALARIO,LOC FROM EMPLE
JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
WHERE DEPART.DEPT_NO=10
--EJ2
SELECT APELLIDO,SALARIO,DNOMBRE FROM EMPLE 
JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
WHERE DEPART.LOC !='SEVILLA'
--EJ3 
SELECT EMP_NO, DNOMBRE, EMPLE.DEPT_NO "ORDENADOS DEPT_NO",SALARIO"ORDENADOS SALARIO" FROM EMPLE 
JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
WHERE EMPLE.SALARIO > 1500  ORDER BY EMPLE.DEPT_NO, EMPLE.SALARIO
--TABLAS ALUMNOS,ASIGNATURAS, NOTAS
--EJ4
SELECT DISTINCT APENOM,ALUMNOS.DNI,POBLA,NOMBRE,NOTA FROM ALUMNOS 
JOIN NOTAS ON ALUMNOS.DNI = NOTAS.DNI 
JOIN ASIGNATURAS ON ASIGNATURAS.COD = NOTAS.COD
WHERE NOTAS.NOTA <5
--EJ5
SELECT NOMBRE, ASIGNATURAS.COD, NOTA  FROM ASIGNATURAS
JOIN  NOTAS ON ASIGNATURAS.COD = NOTAS.COD
WHERE NOTAS.NOTA = 7 OR NOTAS.NOTA=8
--EJ6
SELECT APENOM FROM ALUMNOS
JOIN NOTAS ON ALUMNOS.DNI = NOTAS.DNI
JOIN ASIGNATURAS ON ASIGNATURAS.COD = NOTAS.COD
WHERE NOTAS.NOTA BETWEEN 6 AND 8 AND ASIGNATURAS.NOMBRE = 'BBDD'
--EJ7
SELECT DISTINCT APENOM FROM ALUMNOS
JOIN NOTAS ON ALUMNOS.DNI = NOTAS.DNI
WHERE NOTAS.NOTA < 5
--EJ8
SELECT ALUMNOS.*, ASIGNATURAS.NOMBRE FROM ALUMNOS
JOIN NOTAS ON NOTAS.DNI = ALUMNOS.DNI
JOIN ASIGNATURAS ON ASIGNATURAS.COD = NOTAS.COD
WHERE NOTAS.NOTA >= 5 ORDER BY ASIGNATURAS.NOMBRE
--Tablas Zonas, Emple_Parque, Atracciones, Averias_Parque
--EJ9
SELECT NOM_ATRACCION "Atracciones Averiadas" FROM ATRACCIONES
JOIN AVERIAS_PARQUE ON AVERIAS_PARQUE.COD_ATRACCION = ATRACCIONES.COD_ATRACCION
WHERE FECHA_ARREGLO IS NULL
--EJ10
SELECT NOM_EMPLEADO FROM EMPLE_PARQUE
JOIN AVERIAS_PARQUE ON AVERIAS_PARQUE.DNI_EMPLE = EMPLE_PARQUE.DNI_EMPLE
WHERE FECHA_ARREGLO IS NULL
--EJ11
SELECT ZONAS.*, NOM_EMPLEADO FROM ZONAS
JOIN EMPLE_PARQUE ON EMPLE_PARQUE.DNI_EMPLE = ZONAS.DNI_ENCARGADO
ORDER BY EMPLE_PARQUE.ALTA_EMPRESA
--EJ12
SELECT NOM_EMPLEADO, NOM_ATRACCION, PRESUPUESTO FROM EMPLE_PARQUE
JOIN AVERIAS_PARQUE ON AVERIAS_PARQUE.DNI_EMPLE = EMPLE_PARQUE.DNI_EMPLE
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
JOIN ZONAS ON ZONAS.DNI_ENCARGADO = EMPLE_PARQUE.DNI_EMPLE
WHERE TO_CHAR(FECHA_FALLA, 'YYYY') = '2013'
--EJ13
SELECT AVERIAS_PARQUE.DNI_EMPLE, ATRACCIONES.NOM_ATRACCION, ZONAS.NOM_ZONA, AVERIAS_PARQUE.DNI_EMPLE FROM AVERIAS_PARQUE
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
JOIN ZONAS ON ZONAS.NOM_ZONA = ATRACCIONES.NOM_ZONA
WHERE FECHA_ARREGLO IS NULL 
--EJ14
-
--EJ15
SELECT E1.DNI_EMPLE, ATRACCIONES.NOM_ATRACCION, ZONAS.NOM_ZONA, E2.DNI_EMPLE,E2.NOM_EMPLEADO FROM AVERIAS_PARQUE
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
JOIN ZONAS ON ZONAS.NOM_ZONA = ATRACCIONES.NOM_ZONA
JOIN EMPLE_PARQUE E1 ON E1.DNI_EMPLE = ZONAS.DNI_ENCARGADO
JOIN EMPLE_PARQUE E2 ON E2.DNI_EMPLE = AVERIAS_PARQUE.DNI_EMPLE
WHERE FECHA_ARREGLO IS NULL 
--EJ16
SELECT DISTINCT ZONAS.*, EMPLE_PARQUE.NOM_EMPLEADO FROM ZONAS 
JOIN EMPLE_PARQUE ON EMPLE_PARQUE.DNI_EMPLE = ZONAS.DNI_ENCARGADO
JOIN AVERIAS_PARQUE ON AVERIAS_PARQUE.DNI_EMPLE = ZONAS.DNI_ENCARGADO
WHERE UPPER(NOM_EMPLEADO)='LUIS PÉREZ' AND FECHA_ARREGLO IS NOT NULL
--EJ17
SELECT DISTINCT NOM_ATRACCION, EMPLE_PARQUE.NOM_EMPLEADO FROM ATRACCIONES 
JOIN AVERIAS_PARQUE ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
JOIN EMPLE_PARQUE ON EMPLE_PARQUE.DNI_EMPLE = AVERIAS_PARQUE.DNI_EMPLE
WHERE (UPPER(NOM_EMPLEADO) LIKE 'LUIS%' OR UPPER(NOM_EMPLEADO) LIKE '%IGNACIO%') AND FECHA_ARREGLO IS NOT NULL
--EJ18
SELECT DISTINCT ATRACCIONES.* ,ZONAS.DNI_ENCARGADO,AVERIAS_PARQUE.FECHA_ARREGLO FROM ATRACCIONES 
JOIN AVERIAS_PARQUE ON AVERIAS_PARQUE.COD_ATRACCION = ATRACCIONES.COD_ATRACCION
JOIN EMPLE_PARQUE ON EMPLE_PARQUE.DNI_EMPLE = AVERIAS_PARQUE.DNI_EMPLE
JOIN ZONAS ON ZONAS.DNI_ENCARGADO = EMPLE_PARQUE.DNI_EMPLE
WHERE FECHA_ARREGLO IS NOT NULL