--Ej1
SELECT APENOM, TELEF FROM ALUMNOS WHERE TELEF LIKE '%5%5%'
--Ej2
SELECT DISTINCT DNI FROM NOTAS WHERE NOTA >= 6
--Ej3
SELECT * FROM ALUMNOS WHERE UPPER(POBLA) != 'MADRID'
--Ej4
SELECT DISTINCT COD FROM NOTAS WHERE NOTA < 5 OR NOTA = 9
--Ej5
SELECT NOTA+1 FROM NOTAS WHERE NOTA<5
SELECT NOTA, NOTA+1 "Nota subida" FROM NOTAS WHERE NOTA<5