--Tablas del usuario HR
--1
SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, CITY FROM DEPARTMENTS
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
--2
SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, CITY, COUNTRY_NAME FROM DEPARTMENTS
JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
JOIN COUNTRIES ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID
--3
SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, CITY, COUNTRY_NAME FROM DEPARTMENTS
JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
JOIN COUNTRIES ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID
WHERE COUNTRY_NAME = 'United States of America'
--4
SELECT FIRST_NAME, LAST_NAME, JOB_TITLE FROM EMPLOYEES
JOIN JOBS ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
JOIN JOB_HISTORY ON JOB_HISTORY.EMPLOYEE_ID = EMPLOYEES.JOB_ID