--TABLAS DEPART Y EMPLE
--EJ1
SELECT COUNT(APELLIDO) FROM EMPLE WHERE SUBSTR(APELLIDO,1,1)='A'
--EJ2
SELECT ROUND(AVG(SALARIO),2),COUNT(COMISION),MAX(SALARIO),MIN(SALARIO) FROM EMPLE WHERE DEPT_NO=30
--EJ3
SELECT DISTINCT COUNT(EMP_NO),COUNT(OFICIO) FROM EMPLE
JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
WHERE depart.dnombre='VENTAS'
--EJ4
SELECT APELLIDO,SALARIO,OFICIO FROM EMPLE WHERE UPPER(OFICIO) != 'PRESIDENTE' AND SALARIO=(SELECT MAX(SALARIO) FROM EMPLE WHERE UPPER(OFICIO) != 'PRESIDENTE')
--EJ5
SELECT * FROM EMPLE WHERE UPPER(OFICIO) = 'EMPLEADO' AND SALARIO = (SELECT MAX(SALARIO) FROM EMPLE WHERE UPPER(OFICIO) = 'EMPLEADO')
--EJ6
SELECT APELLIDO FROM EMPLE WHERE SALARIO >= (SELECT AVG(SALARIO) FROM EMPLE)
--EJ7
SELECT SALARIO,ROUND((SALARIO*3.21/100+SALARIO), 1) "Salario Incrementado" FROM EMPLE
--TABLAS ALUMNOS,ASIGNATURAS,NOTAS
--EJ8
SELECT APENOM,ROUND(NOTA,1) FROM NOTAS 
JOIN ALUMNOS ON ALUMNOS.DNI = NOTAS.DNI
WHERE UPPER(APENOM) LIKE '%ELENA'
--EJ9
SELECT POBLA,APENOM,NOTA FROM NOTAS
JOIN ALUMNOS ON ALUMNOS.DNI = NOTAS.DNI
WHERE UPPER(POBLA)='MADRID' AND NOTA = (SELECT MIN(NOTA)FROM NOTAS)
--EJ10--
SELECT APENOM,NOTA,NOMBRE FROM ALUMNOS
JOIN NOTAS ON NOTAS.DNI = ALUMNOS.DNI
JOIN ASIGNATURAS ON NOTAS.COD = ASIGNATURAS.COD
WHERE UPPER(ASIGNATURAS.NOMBRE) ='BBDD' AND NOTA = (SELECT MIN(NOTA) FROM NOTAS WHERE ASIGNATURAS.COD=NOTAS.COD)
--EJ11
SELECT DISTINCT NOTA FROM NOTAS 
JOIN ASIGNATURAS ON NOTAS.COD=ASIGNATURAS.COD
WHERE UPPER(NOMBRE) = 'MARCAS'
--TABLAS ZONAS,EMPLE,PARQUE_ATRACCIONES,AVERIAS_PARQUE
--EJ12
SELECT DISTINCT NOM_EMPLEADO,COUNT(*) "Atracciones Arregladas" FROM EMPLE_PARQUE
JOIN AVERIAS_PARQUE ON EMPLE_PARQUE.DNI_EMPLE = AVERIAS_PARQUE.DNI_EMPLE
WHERE UPPER(NOM_EMPLEADO)='IGNACIO PEÑA' AND FECHA_ARREGLO IN (SELECT (FECHA_ARREGLO) FROM AVERIAS_PARQUE WHERE UPPER(NOM_EMPLEADO)='IGNACIO PEÑA' AND FECHA_ARREGLO IS NOT NULL)
GROUP BY NOM_EMPLEADO
--EJ13
SELECT COUNT(COD_ATRACCION) "Atracciones" FROM ATRACCIONES
WHERE UPPER(NOM_ZONA)='GRAN MAQUINARIA'
--EJ14
SELECT COUNT(COD_ATRACCION) "AVERIAS" FROM AVERIAS_PARQUE
JOIN ZONAS ON ATRACCIONES.NOM_ZONA = ZONAS.NOM_ZONA
JOIN ATRACCIONES ON AVERIAS_PARQUE.COD_ATRACCION = ATRACCIONES.COD_ATRACCION
WHERE UPPER(ZONAS.NOM_ZONA)='GRAN MAQUINARIA'
--EJ15
SELECT AVERIAS_PARQUE.COD_ATRACCION,NOM_ATRACCION,FECHA_FALLA "ULTIMA_AVERIA" FROM AVERIAS_PARQUE 
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
WHERE FECHA_FALLA = (SELECT MAX(FECHA_FALLA) FROM AVERIAS_PARQUE)
--EJ16
SELECT AVERIAS_PARQUE.COD_ATRACCION,NOM_ATRACCION,COSTE_AVERIA "MÁXIMO COSTE" FROM AVERIAS_PARQUE
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
WHERE COSTE_AVERIA = (SELECT MAX(COSTE_AVERIA) FROM AVERIAS_PARQUE)