--Ej1
SELECT FIRST_NAME, LAST_NAME, REPLACE(PHONE_NUMBER, '.', '-') FROM EMPLOYEES
--Ej2
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12 >= 15
--EJ3
SELECT CITY FROM LOCATIONS WHERE SUBSTR(POSTAL_CODE, 1, 1) = SUBSTR(POSTAL_CODE, -1, 1)
--EJ4
SELECT EMP.EMPLOYEE_ID, EMP.DEPARTMENT_ID, TRUNC(MONTHS_BETWEEN(HIS.END_DATE, HIS.START_DATE)) "Meses trabajados" FROM EMPLOYEES EMP
JOIN JOB_HISTORY HIS ON HIS.EMPLOYEE_ID = EMP.EMPLOYEE_ID
--EJ5
SELECT EMP.EMPLOYEE_ID, EMP.DEPARTMENT_ID, TRUNC(MONTHS_BETWEEN(HIS.END_DATE, HIS.START_DATE)) "Meses trabajados" FROM EMPLOYEES EMP
JOIN JOB_HISTORY HIS ON HIS.EMPLOYEE_ID = EMP.EMPLOYEE_ID
WHERE MONTHS_BETWEEN(HIS.END_DATE, HIS.START_DATE) / 12 > 2
--EJ6
SELECT FIRST_NAME, ADD_MONTHS(HIS.START_DATE, 1) - HIS.START_DATE FROM EMPLOYEES EMP
JOIN JOB_HISTORY HIS ON HIS.EMPLOYEE_ID = EMP.EMPLOYEE_ID
--Ej7
SELECT TO_CHAR(TO_DATE('15/MAY/' || (TO_CHAR(SYSDATE, 'YYYY') + 1)), 'day') FROM DUAL
--Ej8 LA PROFESORA DICE QUE NO LA ENTIENDE
--Ej9
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE LENGTH(FIRST_NAME) IN (SELECT LENGTH(FIRST_NAME) FROM EMPLOYEES) AND LENGTH(LAST_NAME) IN (SELECT LENGTH(LAST_NAME) FROM EMPLOYEES)
--EJ10
SELECT FIRST_NAME,LAST_NAME,DECODE(LENGTH(FIRST_NAME),LENGTH(LAST_NAME),'MISMA LONGITUD','DISTINTA LONGITUD')"LONGITUD" FROM EMPLOYEES
--EJ11
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL FROM EMPLOYEES WHERE LOWER(EMAIL) LIKE LOWER(SUBSTR(FIRST_NAME, 1, 1)) || LOWER(LAST_NAME) || '%'  ORDER BY EMPLOYEE_ID
--EJ12
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME, EMAIL FROM EMPLOYEES WHERE UPPER(EMAIL) = CONCAT (UPPER(SUBSTR(FIRST_NAME,1,1)),UPPER(SUBSTR(LAST_NAME,1,LENGTH(EMAIL)-1)))
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME, EMAIL FROM EMPLOYEES WHERE UPPER(EMAIL) = (UPPER(SUBSTR(FIRST_NAME,1,1)) || UPPER(SUBSTR(LAST_NAME,1,LENGTH(EMAIL)-1)))