--EJ1
SELECT OFICIO, TO_CHAR(FECHA_ALT,'month, YYYY')FROM EMPLE WHERE UPPER(OFICIO)='PRESIDENTE'
--EJ2
SELECT * FROM EMPLE WHERE TO_CHAR(FECHA_ALT, 'day') LIKE '%viernes%'
--EJ3
SELECT TO_CHAR(FECHA_ALT,'mm,month') FROM EMPLE WHERE TO_CHAR(FECHA_ALT,'YYYY') = 2007
--EJ4
SELECT APELLIDO,FECHA_ALT,TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA_ALT) / 12) "Antigüedad", LOC FROM EMPLE
JOIN DEPART ON DEPART.DEPT_NO = EMPLE.DEPT_NO
WHERE TO_CHAR(FECHA_ALT,'mm') IN (11, 12)
--EJ5
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA_ALT)/12/3) "Trienios" FROM EMPLE 
JOIN DEPART ON DEPART.DEPT_NO = EMPLE.DEPT_NO
WHERE DNOMBRE IN('INVESTIGACIÓN', 'VENTAS')
--EJ6
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA_ALT) / 12)*200 "Paga especial" FROM EMPLE WHERE TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA_ALT) / 12) > 3
--EJ7
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA_ALT) / 12) "Años trabajados" FROM EMPLE WHERE FECHA_ALT IN (SELECT MIN(FECHA_ALT) FROM EMPLE)
--EJ8
SELECT DEPART.DNOMBRE,TRUNC(MONTHS_BETWEEN(TO_DATE('30/06/2015'), FECHA_ALT) / 12) FROM EMPLE
JOIN DEPART ON DEPART.DEPT_NO = EMPLE.DEPT_NO
WHERE UPPER(DEPART.DNOMBRE)='VENTAS'
--EJ9
SELECT TO_CHAR(FECHA_FALLA, 'HH24:MI')"HORAS MINUTOS", SUBSTR(NOM_ZONA, 1, 3) FROM AVERIAS_PARQUE
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
WHERE UPPER(ATRACCIONES.NOM_ATRACCION) = 'CATARATAS LOCAS'
--EJ10
SELECT TRUNC(TO_NUMBER(FECHA_ARREGLO - FECHA_FALLA)), ATRACCIONES.NOM_ATRACCION, ATRACCIONES.NOM_ZONA, PRESUPUESTO FROM AVERIAS_PARQUE
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
JOIN EMPLE_PARQUE ON EMPLE_PARQUE.DNI_EMPLE = AVERIAS_PARQUE.DNI_EMPLE
JOIN ZONAS ON ZONAS.NOM_ZONA = ATRACCIONES.NOM_ZONA
WHERE FECHA_ARREGLO IS NOT NULL
--EJ11
SELECT ATRACCIONES.NOM_ATRACCION, TRUNC(TO_NUMBER(SYSDATE - FECHA_FALLA)), E2.NOM_EMPLEADO FROM AVERIAS_PARQUE
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
JOIN ZONAS ON ZONAS.NOM_ZONA = ATRACCIONES.NOM_ZONA
JOIN EMPLE_PARQUE E1 ON E1.DNI_EMPLE = ZONAS.DNI_ENCARGADO
JOIN EMPLE_PARQUE E2 ON E2.DNI_EMPLE = AVERIAS_PARQUE.DNI_EMPLE
WHERE FECHA_ARREGLO IS NULL
--EJ12
SELECT SUM(COSTE_AVERIA) FROM AVERIAS_PARQUE WHERE FECHA_ARREGLO IS NOT NULL AND TO_CHAR(FECHA_ARREGLO, 'HH24') >= 18
--EJ13
SELECT * FROM AVERIAS_PARQUE WHERE TO_CHAR(FECHA_FALLA, 'DD') = 15 AND TO_CHAR(FECHA_FALLA, 'MM') BETWEEN 6 AND 12 AND TO_CHAR(FECHA_FALLA, 'YYYY') = 2013
--EJ14
SELECT * FROM AVERIAS_PARQUE
JOIN ATRACCIONES ON ATRACCIONES.COD_ATRACCION = AVERIAS_PARQUE.COD_ATRACCION
WHERE FECHA_ARREGLO IS NOT NULL AND UPPER(ATRACCIONES.NOM_ZONA) = 'INFANTIL' AND (FECHA_ARREGLO - FECHA_FALLA) = (SELECT MAX(FECHA_ARREGLO - FECHA_FALLA) FROM AVERIAS_PARQUE)