--EJ1 
SELECT FIRST_NAME FROM EMPLOYEES
JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE UPPER(DEPARTMENTS.DEPARTMENT_NAME)='SALES' AND SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES WHERE UPPER(DEPARTMENTS.DEPARTMENT_NAME)='SALES')
--EJ2
SELECT COUNTRY_NAME FROM COUNTRIES
JOIN REGIONS ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
WHERE UPPER(REGION_NAME)='ASIA'
--EJ3
SELECT DISTINCT DEPARTMENT_NAME FROM DEPARTMENTS
JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE COMMISSION_PCT IS NOT NULL
--EJ4
SELECT * FROM LOCATIONS 
JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
WHERE UPPER(COUNTRY_NAME) IN('JAPAN','CANADA');
--EJ5
SSELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES
JOIN DEPARTMENTS ON departments.department_id=employees.department_id
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
JOIN COUNTRIES ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID
JOIN REGIONS ON REGIONS.REGION_ID = COUNTRIES.REGION_ID
WHERE UPPER(REGION_NAME)!='EUROPE'
--EJ6
SELECT COUNT(*) FROM EMPLOYEES
JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE UPPER(DEPARTMENT_NAME)='SALES'
--EJ7
SELECT COUNT(*) FROM EMPLOYEES
JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
WHERE UPPER(CITY)='LONDON'
--EJ8 
SELECT FIRST_NAME,EMPLOYEES.MANAGER_ID FROM EMPLOYEES
JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE UPPER(DEPARTMENTS.DEPARTMENT_NAME)='SALES' AND EMPLOYEES.MANAGER_ID=145
--EJ9 
SELECT DEPARTMENT_NAME,COUNT(*) FROM DEPARTMENTS
JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM EMPLOYEES GROUP BY EMPLOYEES.DEPARTMENT_ID)
--EJ10 
SELECT CITY,COUNT(*)FROM LOCATIONS
JOIN DEPARTMENTS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY CITY
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM EMPLOYEES GROUP BY DEPARTMENT_ID )
--EJ11 
SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES EXTERNO
HAVING SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES INTERNO WHERE EXTERNO.DEPARTMENT_ID=INTERNO.DEPARTMENT_ID)
--EJ12 
SELECT COUNT(*)-1 FROM EMPLOYEES
WHERE MANAGER_ID=100 
--EJ13
SELECT DEPARTMENT_NAME,SUM(SALARY) FROM DEPARTMENTS
JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING SUM(SALARY) > 50000
--EJ14
SELECT FIRST_NAME FROM EMPLOYEES
JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
JOIN LOCATIONS ON  LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
JOIN REGIONS ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
WHERE UPPER(REGION_NAME)='EUROPE'
--EJ15
SELECT FIRST_NAME FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES 
JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID WHERE UPPER(JOB_TITLE)='PROGRAMMER')
--EJ16
SELECT FIRST_NAME FROM EMPLOYEES
JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE UPPER(DEPARTMENT_NAME)='SALES' AND SALARY IN (SELECT SALARY FROM EMPLOYEES 
JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID WHERE UPPER(DEPARTMENT_NAME)='ACCOUNTING')
--EJ17
SELECT DEPARTMENTS.DEPARTMENT_ID,COUNT(*) FROM DEPARTMENTS
JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_ID
HAVING COUNT(*) = (SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID=30)
--EJ18
SELECT EMPLOYEES.DEPARTMENT_ID,FIRST_NAME,LAST_NAME,TO_NUMBER(END_DATE-START_DATE) "ANTIGUEDAD" FROM EMPLOYEES
JOIN JOB_HISTORY ON EMPLOYEES.DEPARTMENT_ID = JOB_HISTORY.DEPARTMENT_ID
WHERE  TO_NUMBER(END_DATE-START_DATE) = (SELECT MAX(END_DATE-START_DATE) FROM JOB_HISTORY)