--tablas depart y emple
--EJERCICIO 1--
SELECT * FROM DEPART WHERE UPPER(LOC)='MADRID';
--EJERCICIO 2--
SELECT * FROM DEPART WHERE UPPER(LOC)='MADRID' OR LOC='BARCELONA'
SELECT * FROM DEPART WHERE UPPER(LOC) IN('MADRID', 'BARCELONA')
--EJERCICIO 3---
SELECT * FROM EMPLE WHERE UPPER(OFICIO)='VENDEDOR' AND SALARIO>1500
--EJERCICIO 4--
SELECT APELLIDO,SALARIO,FECHA_ALT FROM EMPLE WHERE UPPER(OFICIO)='ANALISTA' AND DEPT_NO = '20'
--EJERCICIO 5--
SELECT * FROM EMPLE WHERE DIR IS NULL
--EJERCICIO 6--
SELECT * FROM EMPLE WHERE DIR IS NOT NULL AND SALARIO>12000
--EJERCICIO 7--
SELECT APELLIDO,OFICIO FROM EMPLE WHERE UPPER(APELLIDO) LIKE '%E%E%'
--EJERCICIO 8--
SELECT * FROM EMPLE WHERE (UPPER(APELLIDO) LIKE 'M%' OR UPPER(APELLIDO) LIKE 'S%' OR UPPER(APELLIDO) LIKE 'C%') OR (FECHA_ALT BETWEEN '1-1-2008' AND '31-12-2008')
SELECT * FROM EMPLE WHERE (UPPER(APELLIDO) LIKE 'M%' OR UPPER(APELLIDO) LIKE 'S%' OR UPPER(APELLIDO) LIKE 'C%') OR (TO_CHAR(FECHA_ALT, 'YYYY') = '2008')
--EJERCICIO 9--
SELECT * FROM EMPLE WHERE UPPER(APELLIDO) LIKE '%O' OR (SUBSTR(UPPER(APELLIDO), 2, 1) = 'A' OR SUBSTR(UPPER(APELLIDO), 2, 1) = 'E')
SELECT * FROM EMPLE WHERE UPPER(APELLIDO) LIKE '%O' OR (SUBSTR(UPPER(APELLIDO), 2, 1) IN('A', 'E'))
SELECT * FROM EMPLE WHERE UPPER(APELLIDO) LIKE '%O' OR (UPPER(APELLIDO) LIKE '_A%' OR UPPER(APELLIDO) LIKE '_E%')
--EJERCICIO 10--
SELECT * FROM EMPLE WHERE LENGTH(APELLIDO) >= 5
--EJERCICIO 11--
SELECT * FROM EMPLE WHERE DEPT_NO IN(10, 20, 30, 40) OR SALARIO<1000
--EJERCICIO 12--
SELECT * FROM EMPLE WHERE DIR='7839' AND (SALARIO BETWEEN 2900 AND 3100)
--EJERCICIO 13--
SELECT * FROM EMPLE WHERE SALARIO*12>25000
--EJERCICIO 14--
SELECT * FROM EMPLE WHERE (COMISION IS NULL OR COMISION=0) OR COMISION<400
--EJERCICIO 15--
SELECT * FROM EMPLE WHERE SALARIO+(SALARIO*8/100) <1500 ORDER BY DEPT_NO
--EJERCICIO 16--
SELECT * FROM EMPLE WHERE upper(OFICIO) NOT IN ('DIRECTOR','PRESIDENTE') AND SALARIO > 2800
--EJERCICIO 17--
SELECT * FROM EMPLE WHERE OFICIO IN('DIRECTOR','ANALISTA') AND DEPT_NO=20
--EJERCICIO 18--
SELECT * FROM EMPLE WHERE FECHA_ALT BETWEEN '1-1-2005' AND '31-12-2005'
SELECT * FROM EMPLE WHERE TO_CHAR(FECHA_ALT, 'YYYY') = '2005'
--EJERCICIO 19--
SELECT EMP_NO,APELLIDO,(SALARIO*166.3860) salario_pesetas FROM EMPLE

--tablas alumnos, asignaturas y notas
--Ej1
SELECT APENOM, TELEF FROM ALUMNOS WHERE TELEF LIKE '%5%5%'
--Ej2
SELECT DISTINCT DNI FROM NOTAS WHERE NOTA >= 6
--Ej3
SELECT * FROM ALUMNOS WHERE UPPER(POBLA) != 'MADRID'
--Ej4
SELECT DISTINCT COD FROM NOTAS WHERE NOTA < 5 OR NOTA = 9
--Ej5
SELECT NOTA+1 FROM NOTAS WHERE NOTA<5
SELECT NOTA, NOTA+1 "Nota subida" FROM NOTAS WHERE NOTA<5