--TABLA EMPLEADOS Y DEPARTAMENTOS
--EJ1
SELECT OFICIO,MAX(SALARIO),SUM(SALARIO),COUNT(COMISION)FROM EMPLE
GROUP BY OFICIO
--EJ2
SELECT DEPART.DEPT_NO ,DEPART.DNOMBRE,SUM(SALARIO)FROM DEPART
JOIN EMPLE ON EMPLE.DEPT_NO = DEPART.DEPT_NO
GROUP BY DEPART.DEPT_NO ,DEPART.DNOMBRE
HAVING SUM(SALARIO)>9000
--EJ3
SELECT DEPART.DEPT_NO,TRUNC(AVG(SALARIO), 2) FROM EMPLE
JOIN DEPART ON depart.dept_no = EMPLE.DEPT_NO
GROUP BY DEPART.DNOMBRE, depart.dept_no
HAVING COUNT(*)>3 AND UPPER(DNOMBRE) NOT IN('PRESIDENTE','DIRECTOR')
--EJ4
SELECT TO_CHAR(FECHA_ALT, 'MM'), TO_CHAR(FECHA_ALT, 'YYYY'), COUNT(*) FROM EMPLE
GROUP BY TO_CHAR(FECHA_ALT, 'MM'), TO_CHAR(FECHA_ALT, 'YYYY')
--EJ5
SELECT TO_CHAR(FECHA_ALT, 'YYYY') FROM EMPLE
GROUP BY TO_CHAR(FECHA_ALT, 'YYYY')
HAVING COUNT(TO_CHAR(FECHA_ALT, 'YYYY')) = (
    SELECT MAX(COUNT(*) FROM EMPLE
    GROUP BY TO_CHAR(FECHA_ALT, 'YYYY')
)
--EJ6
SELECT TO_CHAR(FECHA_ALT, 'YYYY') FROM EMPLE
WHERE OFICIO!='DIRECTOR'
GROUP BY TO_CHAR(FECHA_ALT, 'YYYY')
HAVING COUNT(TO_CHAR(FECHA_ALT, 'YYYY')) = (
    SELECT MAX(COUNT(*)) FROM EMPLE
    WHERE OFICIO!='DIRECTOR'
    GROUP BY TO_CHAR(FECHA_ALT, 'YYYY'))
  
--EJ7
SELECT ASIG.NOMBRE, NOTA FROM NOTAS
JOIN ASIGNATURAS ASIG ON ASIG.COD = NOTAS.COD
GROUP BY ASIG.NOMBRE, NOTA 
HAVING NOTA = (SELECT MAX(NOTA) FROM NOTAS) OR NOTA = (SELECT MIN(NOTA) FROM NOTAS)
--EJ8
SELECT ASIG.NOMBRE FROM NOTAS
JOIN ASIGNATURAS ASIG ON ASIG.COD = NOTAS.COD
WHERE NOTA<5
GROUP BY ASIG.NOMBRE
HAVING COUNT(NOTA)>1
--EJ9
SELECT APENOM, AVG(NOTAS.NOTA) FROM ALUMNOS
JOIN NOTAS ON NOTAS.DNI = ALUMNOS.DNI
GROUP BY APENOM
HAVING AVG(NOTAS.NOTA) >= 6
--EJ10
SELECT ASIG.COD, ASIG.NOMBRE, COUNT(NOTA) FROM ASIGNATURAS ASIG
JOIN NOTAS ON NOTAS.COD = ASIG.COD
GROUP BY ASIG.COD, ASIG.NOMBRE, NOTA
HAVING NOTA < 5 AND COUNT(NOTAS.NOTA) = (
    SELECT COUNT(NOTAS.NOTA) FROM NOTAS
    WHERE NOTAS.NOTA < 5)
--EJ11
SELECT APENOM FROM ALUMNOS
JOIN NOTAS ON NOTAS.DNI = ALUMNOS.DNI
GROUP BY APENOM, NOTA
HAVING NOTA > 8
--EJ12
SELECT APENOM "NOMBRE",SUM(DECODE(NOTA,'1',1,'2',1,'3',1,'4',1,0)) "SUSPENSOS" ,
COUNT(*) - SUM(DECODE(NOTA,'1',1,'2',1,'3',1,'4',1,0)) "APROBADOS"
FROM ALUMNOS
JOIN NOTAS ON ALUMNOS.DNI = NOTAS.DNI
GROUP BY APENOM;

