--act1
INSERT INTO EMPLE 
SELECT 2000, 'SAAVEDRA', OFICIO, DIR, SYSDATE, SALARIO*20/100 + SALARIO, COMISION, DEPT_NO
FROM EMPLE
WHERE UPPER(APELLIDO)='SALA'

--act2
UPDATE EMPLE SET SALARIO = SALARIO + 100, COMISION + 10 WHERE DEPT_NO = 10;

--act3