-- INSERT
-- 1
INSERT INTO DEPARTAMENTOS VALUES (55, 'RECURSOS', 'MADRID');

-- 2
INSERT INTO EMPLEADOS VALUES (8000, 'ESCUDERO', 'EMPLEADO', NULL, SYSDATE, 1230, NULL, 55);

-- 3
INSERT INTO EMPLEADOS
SELECT 8001, 'ROJO', OFICIO, DIR, SYSDATE - 1, SALARIO, COMISION, DEPT_NO
FROM EMPLEADOS
WHERE EMP_NO = 7654;

-- 4
INSERT INTO EMPLEADOS
SELECT 9050, 'SALVATIERR', 'BECARIO', DIR, NEXT_DAY(SYSDATE, 'LUNES'), SALARIO / 2, NULL, DEPT_NO
FROM EMPLEADOS
WHERE UPPER(APELLIDO) = 'SALA';

-- 5
INSERT INTO DEPARTAMENTOS
SELECT 65, 'I+D', LOC
FROM DEPARTAMENTOS
JOIN EMPLEADOS ON EMPLEADOS.DEPT_NO = DEPARTAMENTOS.DEPT_NO
GROUP BY DEPARTAMENTOS.DEPT_NO, LOC
HAVING COUNT(*) = 
	(SELECT MIN(COUNT(*)) FROM EMPLEADOS
	GROUP BY DEPT_NO);

-- 6
INSERT INTO AVERIAS_PARQUE
SELECT 
-- 7
INSERT INTO ATRACCIONES
SELECT 'A140', 'Qué Miedo', SYSDATE + 30, 40, NOMZONA
FROM ATRACCIONES
GROUP BY NOMZONA
HAVING COUNT(*) = (SELECT MIN(COUNT(*)) FROM ATRACCIONES GROUP BY NOMZONA)

-- UPDATE
-- 8
UPDATE ALUMNOS 
SET DIREC = 'c/ Valbuena 87 1A' 
WHERE UPPER(SUBSTR(APENOM, 1, INSTR(APENOM, ',', 1))) LIKE '%CERRATO%'
-- 9
UPDATE AVERIAS_PARQUE
SET FECHA_ARREGLO = SYSDATE, COSTE_AVERIA = 1200 
WHERE COD_ATRACCION = 'C100' AND FECHA_ARREGLO IS NULL
-- 10
UPDATE EMPLEADOS
SET COMISION = 300
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPARTAMENTOS WHERE LOC = 'BARCELONA') AND COMISION IS NULL
-- 11
UPDATE EMPLEADOS
SET (OFICIO, SALARIO) = (SELECT OFICIO, SALARIO FROM EMPLEADOS WHERE APELLIDO = 'ALONSO')
WHERE APELLIDO = 'TOVAR'
-- 12
UPDATE EMPLEADOS
SET SALARIO = SALARIO + 150
WHERE TO_CHAR(FECHA_ALT, 'YYYY') < 2006
-- 13
UPDATE EMPLEADOS
SET SALARIO = SALARIO + 100
WHERE SALARIO = (SELECT MIN(SALARIO) FROM EMPLEADOS)
-- 14
UPDATE EMPLEADOS
SET SALARIO = SALARIO * 1.10
WHERE (OFICIO, SALARIO) IN (SELECT OFICIO, MIN(SALARIO) FROM EMPLEADOS GROUP BY OFICIO)

-- 15
UPDATE EMPLEADOS
SET SALARIO = SALARIO + 50
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPARTAMENTOS WHERE DNOMBRE = 'INVESTIGACIÓN') AND
	SALARIO <= (SELECT AVG(SALARIO) FROM EMPLEADOS WHERE DEPT_NO = 
		(SELECT DEPT_NO FROM DEPARTAMENTOS WHERE DNOMBRE = 'INVESTIGACIÓN'));