CREATE TABLE PEDIDOS(
    NIF VARCHAR2 (10),
    ARTICULO VARCHAR2 (20),
    COD_FABRICANTE number(3),
    PESO number(3),
    CATEGORIA VARCHAR2(10),
    FECHA_PEDIDO date,
    UNIDADES_PEDIDAS number(4),
    CONSTRAINT PK_PEDIDOS PRIMARY KEY (NIF,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,FECHA_PEDIDO),
    CONSTRAINT FK_PEDIDOS1 FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES,
    CONSTRAINT UNIDADES_PEDIDAS check (UNIDADES_PEDIDAS>0),
    CONSTRAINT CATEGORIA1 check (CATEGORIA IN('PRIMERA','SEGUNDA','TERCERA')),
    CONSTRAINT FK_PEDIDOS2 FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO , CATEGORIA) REFERENCES ARTICULOS,
    CONSTRAINT FK_PEDIDOS3 FOREIGN KEY (NIF) REFERENCES TIENDAS
);
CREATE TABLE VENTAS(
    NIF VARCHAR2(10),
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    FECHA_VENTA DATE,
    UNIDADES_VENDIDAS NUMBER(4),
    CONSTRAINT pk_ventas primary key (NIF, ARTICULO,COD_FABRICANTE, PESO, CATEGORIA ,FECHA_VENTA),
    CONSTRAINT fk_ventas1 foreign key (COD_FABRICANTE) REFERENCES FABRICANTES,
    CONSTRAINT UNIDADES_VENDIDAS CHECK (UNIDADES_VENDIDAS>0),
    CONSTRAINT CATEGORIA check (CATEGORIA IN('PRIMERA','SEGUNDA','TERCERA')),
    CONSTRAINT FK_VENTAS2 FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO , CATEGORIA) REFERENCES ARTICULOS ON DELETE CASCADE,
    CONSTRAINT FK_VENTAS3 FOREIGN KEY (NIF) REFERENCES TIENDAS
);

CREATE TABLE FABRICANTES(
    COD_FABRICANTE NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(15),
    PAIS VARCHAR2(15), 
    CONSTRAINT CK_NOMBRE  CHECK (NOMBRE=UPPER(NOMBRE)),
    CONSTRAINT CK_PAIS CHECK (PAIS=UPPER(PAIS))
);

CREATE TABLE ARTICULOS(
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    PRECIO_VENTA NUMBER(6,2),
    PRECIO_COSTO NUMBER(6,2),
    EXISTENCIAS NUMBER(5),
    CONSTRAINT PK_ARTICULO PRIMARY KEY (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA),
    CONSTRAINT FK_COD_FABRICANTE FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
    CONSTRAINT CK_PRECIO_VENTA CHECK (PRECIO_VENTA>0),
    CONSTRAINT CK_PRECIO_COSTO CHECK (PRECIO_COSTO>0),
    CONSTRAINT CK_PESO CHECK (PESO>0),
    CONSTRAINT CK_CATEGORIA CHECK (CATEGORIA IN ('PRIMERA','SEGUNDA','TERCERA'))
);

CREATE TABLE TIENDAS (
    nif varchar2(10) primary key
);