REM ********** TABLA MISTEXTOS: *************

DROP TABLE MISTEXTOS cascade constraints; 

CREATE TABLE MISTEXTOS (
 TITULO  VARCHAR2(32),
 AUTOR   VARCHAR2(22),
 EDITORIAL VARCHAR2(15), 
 PAGINA  NUMBER(3)
 ) ;

INSERT INTO MISTEXTOS VALUES ('METODOLOGÍA DE LA PROGRAMACIÓN.', 'ALCALDE GARCÍA', 'MCGRAWHILL',140);
INSERT INTO MISTEXTOS VALUES ('"INFORMÁTICA BÁSICA."', 'GARCÍA GARCERÁN', 'PARANINFO',130);
INSERT INTO MISTEXTOS VALUES ('SISTEMAS OPERATIVOS', 'GARCÍA STRUCH', 'OBSBORNE',300);
INSERT INTO MISTEXTOS VALUES ('SISTEMAS DIGITALES.', 'RUÍZ LOPEZ','PRENTICE HALL',190);
INSERT INTO MISTEXTOS VALUES ('"MANUAL DE C."', 'RUÍZ LOPEZ', 'MCGRAWHILL',340);

COMMIT;


REM ********** TABLA LIBROS: *************

DROP TABLE LIBROS cascade constraints; 

CREATE TABLE LIBROS (
 TITULO  VARCHAR2(32),
 AUTOR   VARCHAR2(22),
 EDITORIAL VARCHAR2(15), 
 PAGINA  NUMBER(3)
 ) ;

INSERT INTO LIBROS VALUES ('LA COLMENA', 'CELA, CAMILO JOSÉ', 'PLANETA',240);
INSERT INTO LIBROS VALUES ('LA HISTORIA DE MI HIJO', 'GORDIMER, NADINE', 'TIEM.MODERNOS',327);
INSERT INTO LIBROS VALUES ('LA MIRADA DEL OTRO', 'G.DELGADO, FERNANDO', 'PLANETA',298);
INSERT INTO LIBROS VALUES ('ÚLTIMAS TARDES CON TERESA','MARSE, JUAN', 'CÍRCULO',350);
INSERT INTO LIBROS VALUES ('LA NOVELA DE P. ANSUREZ', 
'TORRENTE B., GONZALO', 'PLANETA',162);
COMMIT;
